// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: inventory.sql

package inventorydb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (id, name, sku, description, price)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, sku, description, price, created_at
`

type CreateItemParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Sku         string         `json:"sku"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.ID,
		arg.Name,
		arg.Sku,
		arg.Description,
		arg.Price,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO stock_ledger (item_id, warehouse_id, quantity_change, transaction_type, order_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, item_id, warehouse_id, quantity_change, transaction_type, order_id, created_at
`

type CreateLedgerEntryParams struct {
	ItemID          uuid.NullUUID `json:"item_id"`
	WarehouseID     uuid.UUID     `json:"warehouse_id"`
	QuantityChange  int32         `json:"quantity_change"`
	TransactionType string        `json:"transaction_type"`
	OrderID         uuid.NullUUID `json:"order_id"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (StockLedger, error) {
	row := q.db.QueryRowContext(ctx, createLedgerEntry,
		arg.ItemID,
		arg.WarehouseID,
		arg.QuantityChange,
		arg.TransactionType,
		arg.OrderID,
	)
	var i StockLedger
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WarehouseID,
		&i.QuantityChange,
		&i.TransactionType,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, username, role, created_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

type CreateUserRow struct {
	ID        uuid.UUID    `json:"id"`
	Username  string       `json:"username"`
	Role      string       `json:"role"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash, arg.Role)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, name, sku, description, price, created_at
FROM items
WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const getStock = `-- name: GetStock :one
SELECT quantity, updated_at
FROM stock_levels
WHERE warehouse_id = $1 AND item_id = $2
`

type GetStockParams struct {
	WarehouseID uuid.UUID `json:"warehouse_id"`
	ItemID      uuid.UUID `json:"item_id"`
}

type GetStockRow struct {
	Quantity  int32        `json:"quantity"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetStock(ctx context.Context, arg GetStockParams) (GetStockRow, error) {
	row := q.db.QueryRowContext(ctx, getStock, arg.WarehouseID, arg.ItemID)
	var i GetStockRow
	err := row.Scan(&i.Quantity, &i.UpdatedAt)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, created_at
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const setStock = `-- name: SetStock :one
INSERT INTO stock_levels (warehouse_id, item_id, quantity, updated_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
ON CONFLICT (warehouse_id, item_id)
DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = CURRENT_TIMESTAMP
RETURNING warehouse_id, item_id, quantity, updated_at
`

type SetStockParams struct {
	WarehouseID uuid.UUID `json:"warehouse_id"`
	ItemID      uuid.UUID `json:"item_id"`
	Quantity    int32     `json:"quantity"`
}

func (q *Queries) SetStock(ctx context.Context, arg SetStockParams) (StockLevel, error) {
	row := q.db.QueryRowContext(ctx, setStock, arg.WarehouseID, arg.ItemID, arg.Quantity)
	var i StockLevel
	err := row.Scan(
		&i.WarehouseID,
		&i.ItemID,
		&i.Quantity,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStock = `-- name: UpsertStock :one
INSERT INTO stock_levels (warehouse_id, item_id, quantity, updated_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
ON CONFLICT (warehouse_id, item_id)
DO UPDATE SET quantity = stock_levels.quantity + EXCLUDED.quantity, updated_at = CURRENT_TIMESTAMP
RETURNING warehouse_id, item_id, quantity, updated_at
`

type UpsertStockParams struct {
	WarehouseID uuid.UUID `json:"warehouse_id"`
	ItemID      uuid.UUID `json:"item_id"`
	Quantity    int32     `json:"quantity"`
}

func (q *Queries) UpsertStock(ctx context.Context, arg UpsertStockParams) (StockLevel, error) {
	row := q.db.QueryRowContext(ctx, upsertStock, arg.WarehouseID, arg.ItemID, arg.Quantity)
	var i StockLevel
	err := row.Scan(
		&i.WarehouseID,
		&i.ItemID,
		&i.Quantity,
		&i.UpdatedAt,
	)
	return i, err
}
