// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package inventorydb

import (
	"database/sql"

	"github.com/google/uuid"
)

type Item struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Sku         string         `json:"sku"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type StockLedger struct {
	ID              uuid.UUID     `json:"id"`
	ItemID          uuid.NullUUID `json:"item_id"`
	WarehouseID     uuid.UUID     `json:"warehouse_id"`
	QuantityChange  int32         `json:"quantity_change"`
	TransactionType string        `json:"transaction_type"`
	OrderID         uuid.NullUUID `json:"order_id"`
	CreatedAt       sql.NullTime  `json:"created_at"`
}

type StockLevel struct {
	WarehouseID uuid.UUID    `json:"warehouse_id"`
	ItemID      uuid.UUID    `json:"item_id"`
	Quantity    int32        `json:"quantity"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	Role         string       `json:"role"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
