// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package inventorydb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (StockLedger, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetItem(ctx context.Context, id uuid.UUID) (Item, error)
	GetStock(ctx context.Context, arg GetStockParams) (GetStockRow, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	SetStock(ctx context.Context, arg SetStockParams) (StockLevel, error)
	UpsertStock(ctx context.Context, arg UpsertStockParams) (StockLevel, error)
}

var _ Querier = (*Queries)(nil)
