// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: logistics.sql

package logisticsdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const assignCarrier = `-- name: AssignCarrier :one
UPDATE shipments
SET carrier = $2, tracking_number = $3, status = 'ASSIGNED', updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, order_id, item_id, quantity, destination, status, carrier, tracking_number, created_at, updated_at
`

type AssignCarrierParams struct {
	ID             uuid.UUID      `json:"id"`
	Carrier        sql.NullString `json:"carrier"`
	TrackingNumber sql.NullString `json:"tracking_number"`
}

func (q *Queries) AssignCarrier(ctx context.Context, arg AssignCarrierParams) (Shipment, error) {
	row := q.db.QueryRowContext(ctx, assignCarrier, arg.ID, arg.Carrier, arg.TrackingNumber)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ItemID,
		&i.Quantity,
		&i.Destination,
		&i.Status,
		&i.Carrier,
		&i.TrackingNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createShipment = `-- name: CreateShipment :one
INSERT INTO shipments (order_id, item_id, quantity, destination, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, item_id, quantity, destination, status, carrier, tracking_number, created_at, updated_at
`

type CreateShipmentParams struct {
	OrderID     uuid.UUID `json:"order_id"`
	ItemID      uuid.UUID `json:"item_id"`
	Quantity    int32     `json:"quantity"`
	Destination string    `json:"destination"`
	Status      string    `json:"status"`
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error) {
	row := q.db.QueryRowContext(ctx, createShipment,
		arg.OrderID,
		arg.ItemID,
		arg.Quantity,
		arg.Destination,
		arg.Status,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ItemID,
		&i.Quantity,
		&i.Destination,
		&i.Status,
		&i.Carrier,
		&i.TrackingNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShipment = `-- name: GetShipment :one
SELECT id, order_id, item_id, quantity, destination, status, carrier, tracking_number, created_at, updated_at
FROM shipments
WHERE id = $1
`

func (q *Queries) GetShipment(ctx context.Context, id uuid.UUID) (Shipment, error) {
	row := q.db.QueryRowContext(ctx, getShipment, id)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ItemID,
		&i.Quantity,
		&i.Destination,
		&i.Status,
		&i.Carrier,
		&i.TrackingNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShipmentByOrder = `-- name: GetShipmentByOrder :one
SELECT id, order_id, item_id, quantity, destination, status, carrier, tracking_number, created_at, updated_at
FROM shipments
WHERE order_id = $1
`

func (q *Queries) GetShipmentByOrder(ctx context.Context, orderID uuid.UUID) (Shipment, error) {
	row := q.db.QueryRowContext(ctx, getShipmentByOrder, orderID)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ItemID,
		&i.Quantity,
		&i.Destination,
		&i.Status,
		&i.Carrier,
		&i.TrackingNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShipmentStatus = `-- name: UpdateShipmentStatus :one
UPDATE shipments
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, order_id, item_id, quantity, destination, status, carrier, tracking_number, created_at, updated_at
`

type UpdateShipmentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) (Shipment, error) {
	row := q.db.QueryRowContext(ctx, updateShipmentStatus, arg.ID, arg.Status)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ItemID,
		&i.Quantity,
		&i.Destination,
		&i.Status,
		&i.Carrier,
		&i.TrackingNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
