// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package logisticsdb

import (
	"database/sql"

	"github.com/google/uuid"
)

type Shipment struct {
	ID             uuid.UUID      `json:"id"`
	OrderID        uuid.UUID      `json:"order_id"`
	ItemID         uuid.UUID      `json:"item_id"`
	Quantity       int32          `json:"quantity"`
	Destination    string         `json:"destination"`
	Status         string         `json:"status"`
	Carrier        sql.NullString `json:"carrier"`
	TrackingNumber sql.NullString `json:"tracking_number"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}
