// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package logisticsdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignCarrier(ctx context.Context, arg AssignCarrierParams) (Shipment, error)
	CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error)
	GetShipment(ctx context.Context, id uuid.UUID) (Shipment, error)
	GetShipmentByOrder(ctx context.Context, orderID uuid.UUID) (Shipment, error)
	UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) (Shipment, error)
}

var _ Querier = (*Queries)(nil)
